# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cluster.proto
"""Generated protocol buffer code."""

from __future__ import annotations

from google.protobuf import (
    descriptor as _descriptor,
    descriptor_pool as _descriptor_pool,
    symbol_database as _symbol_database,
)
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rcluster.proto\x12\x05proto"V\n\x18\x41ppTwinMemberStatusValue\x12#\n\x06status\x18\x01 \x01(\x0e\x32\x13.proto.MemberStatus\x12\x15\n\rapptwin_count\x18\x02 \x01(\r*P\n\x0cMemberStatus\x12\x19\n\x15UNKNOWN_MEMBER_STATUS\x10\x00\x12\x0c\n\x08STARTING\x10\x01\x12\t\n\x05READY\x10\x02\x12\x0c\n\x08STOPPING\x10\x03\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "cluster_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _MEMBERSTATUS._serialized_start = 112
    _MEMBERSTATUS._serialized_end = 192
    _APPTWINMEMBERSTATUSVALUE._serialized_start = 24
    _APPTWINMEMBERSTATUSVALUE._serialized_end = 110
# @@protoc_insertion_point(module_scope)
