# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cluster.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cluster.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rcluster.proto\x12\x05proto\"V\n\x18\x41ppTwinMemberStatusValue\x12#\n\x06status\x18\x01 \x01(\x0e\x32\x13.proto.MemberStatus\x12\x15\n\rapptwin_count\x18\x02 \x01(\r*P\n\x0cMemberStatus\x12\x19\n\x15UNKNOWN_MEMBER_STATUS\x10\x00\x12\x0c\n\x08STARTING\x10\x01\x12\t\n\x05READY\x10\x02\x12\x0c\n\x08STOPPING\x10\x03\x62\x06proto3'
)

_MEMBERSTATUS = _descriptor.EnumDescriptor(
  name='MemberStatus',
  full_name='proto.MemberStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_MEMBER_STATUS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STARTING', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='READY', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STOPPING', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=112,
  serialized_end=192,
)
_sym_db.RegisterEnumDescriptor(_MEMBERSTATUS)

MemberStatus = enum_type_wrapper.EnumTypeWrapper(_MEMBERSTATUS)
UNKNOWN_MEMBER_STATUS = 0
STARTING = 1
READY = 2
STOPPING = 3



_APPTWINMEMBERSTATUSVALUE = _descriptor.Descriptor(
  name='AppTwinMemberStatusValue',
  full_name='proto.AppTwinMemberStatusValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='proto.AppTwinMemberStatusValue.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='apptwin_count', full_name='proto.AppTwinMemberStatusValue.apptwin_count', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=110,
)

_APPTWINMEMBERSTATUSVALUE.fields_by_name['status'].enum_type = _MEMBERSTATUS
DESCRIPTOR.message_types_by_name['AppTwinMemberStatusValue'] = _APPTWINMEMBERSTATUSVALUE
DESCRIPTOR.enum_types_by_name['MemberStatus'] = _MEMBERSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AppTwinMemberStatusValue = _reflection.GeneratedProtocolMessageType('AppTwinMemberStatusValue', (_message.Message,), {
  'DESCRIPTOR' : _APPTWINMEMBERSTATUSVALUE,
  '__module__' : 'cluster_pb2'
  # @@protoc_insertion_point(class_scope:proto.AppTwinMemberStatusValue)
  })
_sym_db.RegisterMessage(AppTwinMemberStatusValue)


# @@protoc_insertion_point(module_scope)
