# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eventpush.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import custom_components.mbapi2020.proto.acp_pb2 as acp__pb2
import custom_components.mbapi2020.proto.gogo_pb2 as gogo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='eventpush.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'\n\032com.daimler.mbcarkit.proto\220\001\001\320\341\036\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x65ventpush.proto\x12\x05proto\x1a\tacp.proto\x1a\ngogo.proto\"\x83\x03\n\x10\x45ventPushCommand\x12\x10\n\x03vin\x18\x01 \x01(\tR\x03vin\x12\x30\n\x05state\x18\x02 \x01(\x0e\x32\x17.proto.VVA.CommandStateR\x08\x61\x63pState\x12<\n\tcondition\x18\x03 \x01(\x0e\x32\x1b.proto.VVA.CommandConditionR\x0c\x61\x63pCondition\x12\x34\n\x04type\x18\x04 \x01(\x0e\x32\x16.proto.ACP.CommandTypeR\x0e\x61\x63pCommandType\x12\x17\n\nprocess_id\x18\x05 \x01(\x03R\x03pid\x12\x1f\n\x0btracking_id\x18\x06 \x01(\tR\ntrackingId\x12%\n\x0e\x63orrelation_id\x18\x07 \x01(\tR\rcorrelationId\x12\x1f\n\x0b\x65rror_codes\x18\x08 \x03(\x05R\nerrorCodes\x12\x12\n\x04guid\x18\t \x01(\tR\x04guid\x12!\n\x0etimestamp_in_s\x18\n \x01(\x03R\ttimestampB#\n\x1a\x63om.daimler.mbcarkit.proto\x90\x01\x01\xd0\xe1\x1e\x01\x62\x06proto3'
  ,
  dependencies=[acp__pb2.DESCRIPTOR,gogo__pb2.DESCRIPTOR,])




_EVENTPUSHCOMMAND = _descriptor.Descriptor(
  name='EventPushCommand',
  full_name='proto.EventPushCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vin', full_name='proto.EventPushCommand.vin', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='vin', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='proto.EventPushCommand.state', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='acpState', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='condition', full_name='proto.EventPushCommand.condition', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='acpCondition', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='proto.EventPushCommand.type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='acpCommandType', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='process_id', full_name='proto.EventPushCommand.process_id', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='pid', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tracking_id', full_name='proto.EventPushCommand.tracking_id', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='trackingId', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='correlation_id', full_name='proto.EventPushCommand.correlation_id', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='correlationId', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error_codes', full_name='proto.EventPushCommand.error_codes', index=7,
      number=8, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='errorCodes', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='guid', full_name='proto.EventPushCommand.guid', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='guid', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp_in_s', full_name='proto.EventPushCommand.timestamp_in_s', index=9,
      number=10, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='timestamp', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=437,
)

_EVENTPUSHCOMMAND.fields_by_name['state'].enum_type = acp__pb2._VVA_COMMANDSTATE
_EVENTPUSHCOMMAND.fields_by_name['condition'].enum_type = acp__pb2._VVA_COMMANDCONDITION
_EVENTPUSHCOMMAND.fields_by_name['type'].enum_type = acp__pb2._ACP_COMMANDTYPE
DESCRIPTOR.message_types_by_name['EventPushCommand'] = _EVENTPUSHCOMMAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EventPushCommand = _reflection.GeneratedProtocolMessageType('EventPushCommand', (_message.Message,), {
  'DESCRIPTOR' : _EVENTPUSHCOMMAND,
  '__module__' : 'eventpush_pb2'
  # @@protoc_insertion_point(class_scope:proto.EventPushCommand)
  })
_sym_db.RegisterMessage(EventPushCommand)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
