# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eventpush.proto
"""Generated protocol buffer code."""

from __future__ import annotations

from google.protobuf import (
    descriptor as _descriptor,
    descriptor_pool as _descriptor_pool,
    symbol_database as _symbol_database,
)
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import custom_components.mbapi2020.proto.acp_pb2 as acp__pb2
import custom_components.mbapi2020.proto.gogo_pb2 as gogo__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0f\x65ventpush.proto\x12\x05proto\x1a\tacp.proto\x1a\ngogo.proto"\x83\x03\n\x10\x45ventPushCommand\x12\x10\n\x03vin\x18\x01 \x01(\tR\x03vin\x12\x30\n\x05state\x18\x02 \x01(\x0e\x32\x17.proto.VVA.CommandStateR\x08\x61\x63pState\x12<\n\tcondition\x18\x03 \x01(\x0e\x32\x1b.proto.VVA.CommandConditionR\x0c\x61\x63pCondition\x12\x34\n\x04type\x18\x04 \x01(\x0e\x32\x16.proto.ACP.CommandTypeR\x0e\x61\x63pCommandType\x12\x17\n\nprocess_id\x18\x05 \x01(\x03R\x03pid\x12\x1f\n\x0btracking_id\x18\x06 \x01(\tR\ntrackingId\x12%\n\x0e\x63orrelation_id\x18\x07 \x01(\tR\rcorrelationId\x12\x1f\n\x0b\x65rror_codes\x18\x08 \x03(\x05R\nerrorCodes\x12\x12\n\x04guid\x18\t \x01(\tR\x04guid\x12!\n\x0etimestamp_in_s\x18\n \x01(\x03R\ttimestampB \n\x1a\x63om.daimler.mbcarkit.proto\xd0\xe1\x1e\x01\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "eventpush_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"\n\032com.daimler.mbcarkit.proto\320\341\036\001"
    _EVENTPUSHCOMMAND._serialized_start = 50
    _EVENTPUSHCOMMAND._serialized_end = 437
# @@protoc_insertion_point(module_scope)
