# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service-activation.proto
"""Generated protocol buffer code."""

from __future__ import annotations

from google.protobuf import (
    descriptor as _descriptor,
    descriptor_pool as _descriptor_pool,
    symbol_database as _symbol_database,
)
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x18service-activation.proto\x12\x05proto"?\n$AcknowledgeServiceStatusUpdatesByVIN\x12\x17\n\x0fsequence_number\x18\x01 \x01(\x05"9\n\x1e\x41\x63knowledgeServiceStatusUpdate\x12\x17\n\x0fsequence_number\x18\x01 \x01(\x05"\xc0\x01\n\x19ServiceStatusUpdatesByVIN\x12\x17\n\x0fsequence_number\x18\x01 \x01(\x05\x12>\n\x07updates\x18\x02 \x03(\x0b\x32-.proto.ServiceStatusUpdatesByVIN.UpdatesEntry\x1aJ\n\x0cUpdatesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12)\n\x05value\x18\x02 \x01(\x0b\x32\x1a.proto.ServiceStatusUpdate:\x02\x38\x01"\x82\x02\n\x13ServiceStatusUpdate\x12\x17\n\x0fsequence_number\x18\x01 \x01(\x05\x12\x0f\n\x07\x63iam_id\x18\x07 \x01(\t\x12\x0b\n\x03vin\x18\x05 \x01(\t\x12\x16\n\x0e\x65mit_timestamp\x18\x02 \x01(\x03\x12\x1c\n\x14\x65mit_timestamp_in_ms\x18\x08 \x01(\x03\x12\x38\n\x07updates\x18\x06 \x03(\x0b\x32\'.proto.ServiceStatusUpdate.UpdatesEntry\x1a\x44\n\x0cUpdatesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12#\n\x05value\x18\x02 \x01(\x0e\x32\x14.proto.ServiceStatus:\x02\x38\x01*\xb3\x01\n\rServiceStatus\x12\x1a\n\x16SERVICE_STATUS_UNKNOWN\x10\x00\x12\x19\n\x15SERVICE_STATUS_ACTIVE\x10\x01\x12\x1b\n\x17SERVICE_STATUS_INACTIVE\x10\x02\x12%\n!SERVICE_STATUS_ACTIVATION_PENDING\x10\x03\x12\'\n#SERVICE_STATUS_DEACTIVATION_PENDING\x10\x04\x42\x1c\n\x1a\x63om.daimler.mbcarkit.protob\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "service_activation_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"\n\032com.daimler.mbcarkit.proto"
    _SERVICESTATUSUPDATESBYVIN_UPDATESENTRY._options = None
    _SERVICESTATUSUPDATESBYVIN_UPDATESENTRY._serialized_options = b"8\001"
    _SERVICESTATUSUPDATE_UPDATESENTRY._options = None
    _SERVICESTATUSUPDATE_UPDATESENTRY._serialized_options = b"8\001"
    _SERVICESTATUS._serialized_start = 616
    _SERVICESTATUS._serialized_end = 795
    _ACKNOWLEDGESERVICESTATUSUPDATESBYVIN._serialized_start = 35
    _ACKNOWLEDGESERVICESTATUSUPDATESBYVIN._serialized_end = 98
    _ACKNOWLEDGESERVICESTATUSUPDATE._serialized_start = 100
    _ACKNOWLEDGESERVICESTATUSUPDATE._serialized_end = 157
    _SERVICESTATUSUPDATESBYVIN._serialized_start = 160
    _SERVICESTATUSUPDATESBYVIN._serialized_end = 352
    _SERVICESTATUSUPDATESBYVIN_UPDATESENTRY._serialized_start = 278
    _SERVICESTATUSUPDATESBYVIN_UPDATESENTRY._serialized_end = 352
    _SERVICESTATUSUPDATE._serialized_start = 355
    _SERVICESTATUSUPDATE._serialized_end = 613
    _SERVICESTATUSUPDATE_UPDATESENTRY._serialized_start = 545
    _SERVICESTATUSUPDATE_UPDATESENTRY._serialized_end = 613
# @@protoc_insertion_point(module_scope)
