# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vin-events.proto
"""Generated protocol buffer code."""

from __future__ import annotations

from google.protobuf import (
    descriptor as _descriptor,
    descriptor_pool as _descriptor_pool,
    symbol_database as _symbol_database,
)
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10vin-events.proto\x12\x05proto"3\n\tVINUpdate\x12\x11\n\taddedVINs\x18\x01 \x03(\t\x12\x13\n\x0b\x64\x65letedVINs\x18\x02 \x03(\tB\x1c\n\x1a\x63om.daimler.mbcarkit.protob\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "vin_events_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"\n\032com.daimler.mbcarkit.proto"
    _VINUPDATE._serialized_start = 27
    _VINUPDATE._serialized_end = 78
# @@protoc_insertion_point(module_scope)
