# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vin-events.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10vin-events.proto\x12\x05proto\"3\n\tVINUpdate\x12\x11\n\taddedVINs\x18\x01 \x03(\t\x12\x13\n\x0b\x64\x65letedVINs\x18\x02 \x03(\tB\x1c\n\x1a\x63om.daimler.mbcarkit.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vin_events_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.daimler.mbcarkit.proto'
  _globals['_VINUPDATE']._serialized_start=27
  _globals['_VINUPDATE']._serialized_end=78
# @@protoc_insertion_point(module_scope)
