# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vin-events.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vin-events.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'\n\032com.daimler.mbcarkit.proto\220\001\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10vin-events.proto\x12\x05proto\"3\n\tVINUpdate\x12\x11\n\taddedVINs\x18\x01 \x03(\t\x12\x13\n\x0b\x64\x65letedVINs\x18\x02 \x03(\tB\x1f\n\x1a\x63om.daimler.mbcarkit.proto\x90\x01\x01\x62\x06proto3'
)




_VINUPDATE = _descriptor.Descriptor(
  name='VINUpdate',
  full_name='proto.VINUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='addedVINs', full_name='proto.VINUpdate.addedVINs', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='deletedVINs', full_name='proto.VINUpdate.deletedVINs', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=78,
)

DESCRIPTOR.message_types_by_name['VINUpdate'] = _VINUPDATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VINUpdate = _reflection.GeneratedProtocolMessageType('VINUpdate', (_message.Message,), {
  'DESCRIPTOR' : _VINUPDATE,
  '__module__' : 'vin_events_pb2'
  # @@protoc_insertion_point(class_scope:proto.VINUpdate)
  })
_sym_db.RegisterMessage(VINUpdate)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
